[workspace]
authors = ["ken <1610057945@qq.com>"]
channels = ["conda-forge"]
name = "UnifiedReward"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
[dependencies]
python = "3.10.*"
ninja = ">=1.13.1,<2"
gcc = ">=12,<13"
gxx = ">=12,<13"

[pypi-dependencies]
llava = { path = ".", editable = true, extras = ["train"] }
setuptools = ">=80.9.0, <81"
packaging = ">=25.0, <26"
flash-attn = { url = "https://github.com/Dao-AILab/flash-attention/releases/download/v2.5.8/flash_attn-2.5.8+cu122torch2.1cxx11abiFALSE-cp310-cp310-linux_x86_64.whl" }

[pypi-options]
no-build-isolation = ["flash-attn"]

[system-requirements]
cuda = "12"

[feature.diffdpo.dependencies]
python = ">=3.10, <3.11"

[feature.diffdpo.pypi-dependencies]
accelerate = "==0.20.2"
diffusers = "==0.20.0"
torchvision = "*"
transformers = "==4.30.2"
datasets = "*"
ftfy = "*"
tensorboard = "*"
jinja2 = "*"
bitsandbytes = "*"
xformers = "*"
hpsv2 = "*"
openai-clip = "==1.0.1"
huggingface_hub = "==0.25.2"
requests = { version = ">=2.19.0, <2.20.0", extras = [ "socks" ] }

[environments]
diffdpo = { features = ["diffdpo"], no-default-feature = true }
